### ISSUE TITLE
何でここ固定なの？

### ISSUE THREAD

**Issue by c0a21109** [c0a21101/ProjExD#10]
https://github.com/c0a21101/ProjExD/blob/ddf6a501634643be675f7428b7a9b44421962b91/ex04/dodge_bomb.py#L107
x座標はランダムなのになんでy座標は固定値なの？？

**Comment by c0a21101** [comment]
yもランダムにするとこうかとんの上に爆弾が生成されてしまうことがあったので，yを固定することでプレイヤーが必要以上に上に移動さえしなければ生成時の即被弾を回避できると思ったからです。
