### ISSUE TITLE
print内容について

### ISSUE THREAD

**Issue by c0a21109** [c0a21101/ProjExD#3]
https://github.com/c0a21101/ProjExD/blob/ed04d92f0de431aa97d07a3f1aa752d8a59989dc/ex01/alphabet.py#L53
煽りすぎだと思います。
解答権がなくなりました。残念！w
ではなく，
解答権がなくなりました。残念。
の方が印象がいいと思います。

**Comment by c0a21101** [comment]
ありがとうございます。修正しました。
