### ISSUE TITLE
ここ

### ISSUE THREAD

**Issue by c0a21109** [c0a21101/ProjExD#6]
https://github.com/c0a21101/ProjExD/blob/9f6b7f4bbb52e7b79cd5f7f09f7d17c1f6a3213e/ex02/calc.py#L37
四則演算と一緒のとこでやっちゃダメなの？

**Comment by c0a21101** [comment]
四則演算記号の時は記号が隣接していないか、小数点の時はその今入力している数字の中に小数点がないか、と処理の内容が違うので別で設けるほうが処理がしやすいと判断して別にしました。
