### ISSUE TITLE
Start, Goal

### ISSUE THREAD

**Issue by yu-kod** [c0a21101/ProjExD#7]
https://github.com/c0a21101/ProjExD/blob/e4fa32457d96635ed1f27146019c486a1696d7f6/ex03/maze.py#L102
startとgoalはmaze makerで作成をした方が良いと思います。
そうすれば、スタート、ゴール判定を、元の配列から参照できます(道0、壁1、スタート2、ゴール3という風に配列に格納する)

**Comment by c0a21101** [comment]
修正しました。
