### ISSUE TITLE
座標に使ってる変数

### ISSUE THREAD

**Issue by c0a21109** [c0a21101/ProjExD#8]
https://github.com/c0a21101/ProjExD/blob/e4fa32457d96635ed1f27146019c486a1696d7f6/ex03/maze.py#L119
109行目の時は，x軸とy軸の計算を（）内に入れてるのに，ここはわざわざcx,cyにしてるのなんででしょう？

**Comment by c0a21101** [comment]
109行目の計算では四角形を生成するために4頂点の座標が必要だったので計算で求めました。
119行目では中心だけがわかればいいのでcx,cyを使いました。
なお，現在109行目の処理はissue#7の解決時にmaze_maker.pyに移したので本コードでは参照できなくなっていると思います。
