### ISSUE TITLE
冗長な表現

### ISSUE THREAD

**Issue by yu-kod** [c0a21101/ProjExD#9]
https://github.com/c0a21101/ProjExD/blob/ddf6a501634643be675f7428b7a9b44421962b91/ex04/dodge_bomb.py#L64
64~80行目、前半部分と後半部分で符号だけ反転して同様の処理がされています。関数化し引数を変更するか、変数を用意し*-1の演算で符号のみ変更することで繰り返しを解消してください。

**Comment by c0a21101** [comment]
ありがとうございます。修正しました。
